#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /etc/popularity-contest.conf ] ; then
       . /etc/popularity-contest.conf
       if [ yes = "$PARTICIPATE" ] ; then
               PARTICIPATE=true
       else
               PARTICIPATE=false
       fi
       db_set popularity-contest/participate "$PARTICIPATE"
fi

db_input medium popularity-contest/participate || [ $? -eq 30 ]
db_go || true

# Ask if the old addresses should be changed to the new address.
if [ "$MAILTO" = "erich-survey@debian.org" -o \
     "$MAILTO" = "apenwarr-survey@debian.org" ]; then
    db_input high popularity-contest/update-mailto || [ $? -eq 30 ]
    db_go || true
fi
