#!/bin/bash

# Load debconf variables
. /usr/share/debconf/confmodule

conffile=/etc/popularity-contest.conf

set -e

if [ -e $conffile ] ; then
    # Fetch current values.
    . $conffile
fi

if [ -z "$MAILTO" -o "$MAILTO" = "erich-survey@debian.org" ]; then
    MAILTO="apenwarr-survey@debian.org"
fi
if [ -z "$MY_HOSTID" ]; then
    MY_HOSTID=`dd if=/dev/urandom bs=1k count=1 2>/dev/null | md5sum|sed 's/  -//'''`
fi

# Get this setting from debconf.  It was set based on the content of
# /etc/popularity-contest.conf in the 'config' script, so it should be
# safe to ignore the value fetched by loading the file above.  This
# should allow for using debconf to reconfigure the package.
db_get popularity-contest/participate || true
if [ "$RET" = "yes" -o "$RET" = "YES" -o "$RET" = "true" ]; then
    PARTICIPATE="yes"
else
    PARTICIPATE="no"
fi

generate_conffile() {
	cat <<-EOF >$conffile
		# Config file for Debian's popularity-contest package.
		#
		# To change this file, remove it and use:
		#        dpkg-reconfigure popularity-contest
		#
		# You can also edit it by hand, if you so choose.
		
		# MAILTO specifies the address to e-mail statistics to each week.
		#
		MAILTO="$MAILTO"
		
		# MY_HOSTID is a secret number that the popularity-contest receiver
		# uses to keep track of your submissions.  Whenever you send in a
		# new entry, it overwrites the last one that had the same HOSTID.
		#
		# This key was generated automatically so you should normally just
		# leave it alone.
		#
		MY_HOSTID="$MY_HOSTID"
	
		# MAILFROM is the forged sender email address you want to use in
		# email submitted to the popularity-contest.  If this is commented
		# out, no From: or Sender: lines will be added to the outgoing mail,
		# and it will be your MTA's job to add them.  This is usually what
		# you want.
		#
		# If your MTA is misconfigured or impossible to configure correctly,
		# and it always generates invalid From: and/or Sender: lines, you
		# can force different results by setting MAILFROM here.  This can
		# cause problems with spam bouncers, so most people should leave it
		# commented out.
		#
	EOF
	if [ -z "$MAILFROM" ]; then
		echo '#MAILFROM=root@nowhere.org' >> $conffile
	else
		echo "MAILFROM=$MAILFROM" >> $conffile
	fi

	
	cat <<-EOF >> $conffile
	
		# PARTICIPATE can be one of "yes" or "no".
		# If you don't want to participate in the contest, say "no"
		# and we won't send messages.
		#
		# If this option is missing, the default is "no".
		#
		PARTICIPATE=$PARTICIPATE
	EOF
}

case "$1" in
    configure)
	if [ ! -e $conffile ]; then
	    generate_conffile
	else
            # Replace if the value changed, to avoid changing the
	    # config file date when no change was done.
	    if sed "s/^PARTICIPATE=.*$/PARTICIPATE=$PARTICIPATE/" < $conffile > $conffile.new &&
		! cmp $conffile $conffile.new > /dev/null; then
		mv $conffile.new $conffile
	    else
		rm $conffile.new
	    fi
	fi
	;;
    *)
	;;
esac

#DEBHELPER#
