#!/bin/bash

# Load debconf variables
. /usr/share/debconf/confmodule

conffile=/etc/popularity-contest.conf

set -e

if [ -e $conffile ] ; then
    # Fetch current values.
    . $conffile
fi

if [ -z "$MY_HOSTID" ]; then
    MY_HOSTID=`dd if=/dev/urandom bs=1k count=1 2>/dev/null | md5sum|sed 's/  -//'''`
fi

# Get this setting from debconf.  It was set based on the content of
# /etc/popularity-contest.conf in the 'config' script, so it should be
# safe to ignore the value fetched by loading the file above.  This
# should allow for using debconf to reconfigure the package.
db_get popularity-contest/participate || true
if [ "$RET" = "yes" -o "$RET" = "YES" -o "$RET" = "true" ]; then
    PARTICIPATE="yes"
else
    PARTICIPATE="no"
fi

generate_conffile() {
	cat <<-EOF >$conffile
		# Config file for Debian's popularity-contest package.
		#
		# To change this file, use:
		#        dpkg-reconfigure popularity-contest
		#
		# You can also edit it by hand, if you so choose.
		#
		# See /usr/share/popularity-contest/default.conf for more info
		# on the options.
		
		MY_HOSTID="$MY_HOSTID"
		PARTICIPATE="$PARTICIPATE"
	EOF
	# Make sure user nobody can read the file.
	chmod a+r $conffile
}

case "$1" in
    configure)
	if [ ! -e $conffile ]; then
	    generate_conffile
	else
	    # Replace only if the content changed, to avoid changing the
	    # config file date when no change was done.


	    # Commenting out the obsolete addresses, to use the
	    # default config from /usr/share/ on hosts where
	    # the old default was unchanged

	    if sed " \
		s/^PARTICIPATE=.*$/PARTICIPATE=\"$PARTICIPATE\"/;   \
		s/^\(MAILTO=\"erich-survey@debian.org\"\)$/#\1/;    \
		s/^\(MAILTO=\"apenwarr-survey@debian.org\"\)$/#\1/; \
		s/^\(MAILTO=\"survey@popcon.debian.org\"\)$/#\1/;   \
		" < $conffile > $conffile.new &&
		! cmp $conffile $conffile.new > /dev/null; then
		mv $conffile.new $conffile
		# Make sure user nobody can read the file.
		chmod a+r $conffile
	    else
		rm $conffile.new
	    fi
	fi
	;;
    *)
	;;
esac

#DEBHELPER#
